/**
 * ABI for the XorvLog contract.
 *
 * GENERATED by scripts/deploy-log.mts from contracts/XorvLog.sol.
 * Do not edit by hand — re-run the deploy script instead, so the ABI and
 * the contract cannot drift apart.
 */

export const XORV_LOG_ABI = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "size",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "max",
        "type": "uint256"
      }
    ],
    "name": "PayloadTooLarge",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "kind",
        "type": "uint8"
      }
    ],
    "name": "UnknownKind",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint8",
        "name": "kind",
        "type": "uint8"
      },
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "subject",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "author",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "seq",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "payload",
        "type": "string"
      }
    ],
    "name": "Entry",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "KIND_HEARTBEAT",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "KIND_RECEIPT",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "KIND_REGISTRATION",
    "outputs": [
      {
        "internalType": "uint8",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "MAX_PAYLOAD_BYTES",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "kind",
        "type": "uint8"
      },
      {
        "internalType": "bytes32",
        "name": "subject",
        "type": "bytes32"
      },
      {
        "internalType": "string",
        "name": "payload",
        "type": "string"
      }
    ],
    "name": "append",
    "outputs": [
      {
        "internalType": "uint64",
        "name": "seq",
        "type": "uint64"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "count",
    "outputs": [
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
