/**
 * Compile and deploy XorvLog to Arbitrum Sepolia (or whichever XORV_NETWORK is set).
 *
 * Deliberately a script and not a framework. Hardhat or Foundry would each drag
 * in a toolchain and a config surface to deploy one 100-line contract to one
 * chain — solc is a library, viem is already a dependency, and the whole thing
 * is legible in one file.
 *
 * The ABI it emits is the build artifact the rest of the repo imports, so the
 * contract and the code that calls it cannot drift apart:
 *
 *   packages/protocol/src/xorv-log.abi.json
 *
 *   pnpm dlx tsx scripts/deploy-log.mts
 *
 * Gas is ETH on every supported network, paid by the operator key.
 */

import solc from "solc";
import { createPublicClient, createWalletClient, http, formatEther, getContract } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { evmChain } from "../packages/protocol/src/chain.ts";
import { DEFAULT_NETWORK, explorerAddress } from "../packages/protocol/src/constants.ts";
import { readFileSync, writeFileSync } from "node:fs";
import { keccak256, toHex } from "viem";

const root = new URL("../", import.meta.url);
const env = Object.fromEntries(
  readFileSync(new URL(".env", root), "utf8")
    .split("\n")
    .filter((l) => l.trim() && !l.startsWith("#"))
    .map((l) => {
      const i = l.indexOf("=");
      return [l.slice(0, i).trim(), l.slice(i + 1).trim()];
    }),
) as Record<string, string>;

const NAME = "XorvLog";
const source = readFileSync(new URL(`contracts/src/${NAME}.sol`, root), "utf8");

// ---------------------------------------------------------------------------
// Compile
// ---------------------------------------------------------------------------

console.log(`\n  compiling ${NAME}.sol with solc ${solc.version()}`);

const input = {
  language: "Solidity",
  sources: { [`${NAME}.sol`]: { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));
for (const e of output.errors ?? []) {
  console.log(`  ${e.severity}: ${e.formattedMessage.trim()}`);
  if (e.severity === "error") process.exit(1);
}

const artifact = output.contracts[`${NAME}.sol`][NAME];
const abi = artifact.abi;
const bytecode = `0x${artifact.evm.bytecode.object}` as `0x${string}`;
console.log(`  bytecode ${(bytecode.length - 2) / 2} bytes`);

// Emitted as TypeScript rather than JSON on purpose. A `.json` import needs
// `resolveJsonModule` plus a copy step to get the file into `dist/`, and the
// failure when that copy is missed is a runtime module-not-found in a published
// package. A `.ts` file compiles like any other source, and `as const` gives
// viem the literal types it needs to infer event argument names.
writeFileSync(
  new URL("packages/protocol/src/xorv-log.abi.ts", root),
  `/**\n` +
    ` * ABI for the XorvLog contract.\n` +
    ` *\n` +
    ` * GENERATED by scripts/deploy-log.mts from contracts/src/XorvLog.sol.\n` +
    ` * Do not edit by hand — re-run the deploy script instead, so the ABI and\n` +
    ` * the contract cannot drift apart.\n` +
    ` */\n\n` +
    `export const XORV_LOG_ABI = ${JSON.stringify(abi, null, 2)} as const;\n`,
);
console.log("  abi → packages/protocol/src/xorv-log.abi.ts");

// ---------------------------------------------------------------------------
// Deploy
// ---------------------------------------------------------------------------

const network = env.XORV_NETWORK || DEFAULT_NETWORK;
if (env.XORV_RPC_URL) process.env.XORV_RPC_URL = env.XORV_RPC_URL;
const chain = evmChain(network);
const deployer = privateKeyToAccount(env.XORV_OPERATOR_KEY as `0x${string}`);
const transport = http(chain.rpcUrls.default.http[0]);
const publicClient = createPublicClient({ chain, transport });
const wallet = createWalletClient({ account: deployer, chain, transport });

const before = await publicClient.getBalance({ address: deployer.address });
console.log(`\n  network  ${chain.name} (${network})`);
console.log(`  deployer ${deployer.address}`);
console.log(`  balance  ${formatEther(before)} ETH`);
if (before === 0n) {
  console.error(`\n  ✖ deployer holds no ETH. Gas on ${chain.name} is ETH — fund it first.\n`);
  process.exit(1);
}

const hash = await wallet.deployContract({ abi, bytecode, args: [] });
console.log(`  tx       ${hash}`);
const receipt = await publicClient.waitForTransactionReceipt({ hash });
const address = receipt.contractAddress!;
const after = await publicClient.getBalance({ address: deployer.address });

console.log(`  status   ${receipt.status}`);
console.log(`  address  ${address}`);
console.log(`  gas      ${receipt.gasUsed} units = ${formatEther(before - after)} ETH`);

// ---------------------------------------------------------------------------
// Prove it works, rather than assuming a successful deploy means a usable one
// ---------------------------------------------------------------------------

const log = getContract({ address, abi, client: { public: publicClient, wallet } });

const payload = JSON.stringify({
  v: 1,
  kind: "provider.registered",
  at: Date.now(),
  data: { note: "XorvLog deployment smoke test" },
});
const writeHash = await log.write.append([1, keccak256(toHex("deploy-smoke-test")), payload]);
const writeReceipt = await publicClient.waitForTransactionReceipt({ hash: writeHash });

const entries = await publicClient.getContractEvents({
  address,
  abi,
  eventName: "Entry",
  fromBlock: receipt.blockNumber,
});

console.log(`\n  smoke test`);
console.log(`  append   ${writeHash} (${writeReceipt.status})`);
console.log(`  count    ${await log.read.count()}`);
console.log(`  read back ${entries.length} entry/entries from the log`);
for (const e of entries) {
  console.log(`    kind=${e.args.kind} seq=${e.args.seq} author=${e.args.author}`);
  console.log(`    payload=${e.args.payload}`);
}

console.log(`\n  ${explorerAddress(network, address)}`);
console.log(`\n  Add to .env:\n  XORV_LOG_ADDRESS=${address}\n  XORV_LOG_FROM_BLOCK=${receipt.blockNumber}\n`);
