/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IXorvRegistry {
    function initialize(address owner) external;

    function register(bytes32 node_id, string calldata metadata_uri) external;

    function registerFor(address provider, bytes32 node_id, string calldata metadata_uri) external;

    function deactivate() external;

    function heartbeat() external;

    function heartbeatFor(address provider) external;

    function recordOutcome(address provider, bool success, uint256 amount) external;

    function getProvider(address provider) external view returns (bytes32, uint64, uint64, uint64, uint64, uint256, bool);

    function isActive(address provider) external view returns (bool);

    function score(address provider) external view returns (uint32);

    function providerCount() external view returns (uint64);

    function owner() external view returns (address);

    function escrow() external view returns (address);

    function operator() external view returns (address);

    function setEscrow(address escrow) external;

    function setOperator(address operator) external;

    function transferOwnership(address new_owner) external;

    error Unauthorized(address);

    error AlreadyInitialized();

    error NotRegistered(address);

    error ZeroAddress();

    error InvalidNodeId();

    error Inactive(address);

    error MetadataTooLong(uint256);
}
